### ISSUE TITLE
V523 The 'then' statement is equivalent to the 'else' statement. lodepng.cpp 5176

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lvandeve/lpi#1]
```
I did static code check and found:

V523 The 'then' statement is equivalent to the 'else' statement. lodepng.cpp 
5176

Bug or as designed?
```

Original issue reported on code.google.com by `mrpuzz...@gmail.com` on 25 Oct 2013 at 9:23

**Comment by lvandeve** [comment]
Hi,

Sorry for noticing the comment so late, I only noticed it now while exporting from google code to github. This has in the meantime been fixed (at least in https://github.com/lvandeve/lodepng). Thanks for reporting :)

-Lode
